PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cmdb: <http://purl.org/aer/cmdb/1.0/>

SELECT ?s ?label
WHERE
{
  GRAPH <http://aeriandi.com/cmdbTron/ServiceCatalog#Index> 
	{ ?s a cmdb:serviceDependencyGraph  ;	  
	      rdfs:label ?label . 
	} 
}